language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: rIp0p8uRrhIBlykY/f6BlI2BAGbecMkbaWXzI7NmNAM0C6IAXkCU1NS0ns5EB+rjGqifGNhwcYRoH/zEt7rEKqxb7EaLdgZIkD/T+B3VOcT3ZtcTOv73sSN7AMoKyEfoez+hBK1C+whz5AU18/MFdDe9nHLaN1h0Ho4ao/P7LrRXOxNDwGwkoQBrdpjcNtxS1w8sZR5Cpj0M0NEFmT2SjKhPBFOaTpedEODTVrYukM2mSxACOD9gw8zT7Mn/FU6z7nm0tVkUfxtZw6LZrmIMtLRMyy+SvpUTsbXWyp5fcnuTcUK7Tm8kTj6p3nenq3UZkhyYJjbqcJbQ5a0Rsqkb7o1aY7slLDvsy8JuFTUCBJX1esTBJP1GUaFOWDgWwwBTs2LCZP032dBSy6guO0J8YFxjtSlLcithn9E7y9dfbqsBLxOD0hh9TYd8Gy/SFSUEKQlDyxksT/XEyav90F4KaDMta5iUST27L9at5jxHJEPDt7mgF1lsLbYGd2+JO4GHqGqg3weQz27ahzIp6PSYgEZ+SASeDUCL6fxxx8k5PPhZB/AXPYTnb7mzpmNZDG2dd6fBJQBrqtgfus93CcrB8U3710j6tJ/PKICtljHeblNt29L++F/isShGsNY+ituyO8JCw0RR2P/R15T8wZdXWX4/TooNPYJzEEFUakel/C4=
install: /bin/true
script:
  - ./gradlew clean ciBuild
deploy:
  provider: heroku
  api_key:
    secure: UMAIfJ95lRYBGDkIKmuT09MPtmlw3+nzt7rX9kUT23dlf6GpGqaTy2OvVnYehQVqt32U5+IdrRgSD/swiahUcVW/njWoUmITlAbgoJ40zv2ipwIjkzEAiowIpNJYGpRSXrOedk2zbWJQuo54W6x4IT/NG5k2Qz6EunWhszKiNRIWkMFsZcKNLKgg7CY6Fm0GU5CulDNbHmzIuL7CDXcSZb7iGcx8Q73kkS7wRBL2aNDMpxG2Zj9veJWxA18LPD4Tf95owRW95rV2w3OheyB4K1ZpJsl4TmTlRzICngs9QcFRPgcY865RxLvCo9gWn3UwQymEDealgAHBVFGgK5/SsZcziss7U2rw+kHA1MawOZkVXvi9LuG19VuFlltCqz7I0G4qmKffIJprJR3KVTUz9TIJk8ckv+kfSYVbtGcigUDP+RpX7ULyonQhjjHW51xEqtOvuihOodckzlzy6H13n8oRltEZelb4A+rGuNyPXWUMqYkdnl/dvvYdWelFZiNEHLFjWqUz8C5NelzWhHyTqdTE0XPfT478h+i/aw+bjLuA35sv0YDROF922DXrXJmr7veiAxbjevQHyPQjbMymzgESW65q3yyCWWZzt/3RsfD33ghWW/CPv7poGhOW09aa92lHhoAmc44meiNfkO5WJTo6G8Mo7VfWdXDwpLjJnUM=
  app: ct-payone-integration-staging
  on:
    repo: commercetools/commercetools-payone-integration
    branch: master
after_deploy:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - ./gradlew --continue --info :functionaltests:cleanTest publishGhPages || travis_terminate 1
  - ./travis-build.sh || travis_terminate 1
