# https://docs.travis-ci.com/user/languages/java
language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
    secure: cZ0FItWJEGTacfRoYy+Rh9y0QYQEOY3praKn/yLFoj8UdIYBUIZQyK2mDNBOck9EGCK1qt4cTTYpPE28xrmaRdClNg0WHnMwX/8qcyHghaMxnN0YDxYmQLPbfd/fK/D1fmbdB/2PF3GfEUNLBaMjh5t674ocIfyEDFGJN5b8ADizbfgwbE7Xw2PmLjNl5sEh3g77c4P++DxTjSm06NpbBNahv+SE2gMfU80WBaEG8Yo5mFhuQqu5j+cb5EZXT9ndKRpB8hhXVghIRpEeuv0tSJKVvtv3/chsXMC00zAM41V0MXO9Rfjr4fIzJg7hK6Q+Jb/d5RZBJODqzhKlLQo9fw3f8RWteFMn9SvvrA7dfytacLsSCFJU/+mg7Z1WV6rywa119nusQV7Y07KY9z6Z4jUBgYwjPVkESMDH2OOegqbUgQQMCrxZggVqEH1DecwZrgAMxL66XUVb/2pzcqen93Ti3IzhFPTHKtkvnF/OQ0sLxme5xu7yYSH7hFPYG75CGG4HRknr9HuMhE/A5Esgf+prYSiAix6NFmSPczKGMBxG3Mh3sJHl7DvMaDfCbArZUWC3Id6wy5A40dBdDZ9p7q7cLz2yduPrfzggKeX7g/WzpHr+7H9CrGcDfE/JeN+rio2BSzzrft6oqBBDxyedznW05dxSbFKxYv+VqSU/Yco=
